joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: { p: 5000, d: 50, i: 0.0}
joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: { p: 10000, d: 100, i: 0.02}
joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: { p: 10000, d: 50, i: 0.01}
joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: { p: 10000, d: 70, i: 0.01}
joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint5
    pid: { p: 5000, d: 70, i: 0.01}
joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint6
    pid: { p: 3000, d: 50, i: 0.01}
joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint7
    pid: { p: 1000, d: 20, i: 0.0}
